

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mohamed Mafas
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_manageroom = new javax.swing.JButton();
        btn_newstudent = new javax.swing.JButton();
        btn_up_del_student = new javax.swing.JButton();
        btn_student_pay = new javax.swing.JButton();
        btn_studentliving = new javax.swing.JButton();
        btn_leveadstudent = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_shutdown = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_manageroom.setBackground(new java.awt.Color(204, 255, 204));
        btn_manageroom.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_manageroom.setForeground(new java.awt.Color(0, 0, 0));
        btn_manageroom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/room.png"))); // NOI18N
        btn_manageroom.setText("Manage Room");
        btn_manageroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageroomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_manageroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 320, -1));

        btn_newstudent.setBackground(new java.awt.Color(204, 255, 204));
        btn_newstudent.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_newstudent.setForeground(new java.awt.Color(0, 0, 0));
        btn_newstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new student.png"))); // NOI18N
        btn_newstudent.setText("New Student");
        btn_newstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 320, -1));

        btn_up_del_student.setBackground(new java.awt.Color(204, 255, 204));
        btn_up_del_student.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_up_del_student.setForeground(new java.awt.Color(0, 0, 0));
        btn_up_del_student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update & Delete Student.png"))); // NOI18N
        btn_up_del_student.setText("Update & Delete Students");
        btn_up_del_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_up_del_studentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_up_del_student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 320, -1));

        btn_student_pay.setBackground(new java.awt.Color(204, 255, 204));
        btn_student_pay.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_student_pay.setForeground(new java.awt.Color(0, 0, 0));
        btn_student_pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fees.png"))); // NOI18N
        btn_student_pay.setText("Student Fees");
        btn_student_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_student_payActionPerformed(evt);
            }
        });
        getContentPane().add(btn_student_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 320, -1));

        btn_studentliving.setBackground(new java.awt.Color(204, 255, 204));
        btn_studentliving.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_studentliving.setForeground(new java.awt.Color(0, 0, 0));
        btn_studentliving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/all student living.png"))); // NOI18N
        btn_studentliving.setText("Students Living");
        btn_studentliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentlivingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_studentliving, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 320, -1));

        btn_leveadstudent.setBackground(new java.awt.Color(204, 255, 204));
        btn_leveadstudent.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btn_leveadstudent.setForeground(new java.awt.Color(0, 0, 0));
        btn_leveadstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Leaved students.png"))); // NOI18N
        btn_leveadstudent.setText("Leaved Students");
        btn_leveadstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leveadstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_leveadstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 320, -1));

        btn_logout.setBackground(new java.awt.Color(204, 255, 204));
        btn_logout.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(0, 0, 0));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btn_logout.setText("LogOut");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        btn_exit.setBackground(new java.awt.Color(204, 255, 204));
        btn_exit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(0, 0, 0));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close.png"))); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        btn_shutdown.setBackground(new java.awt.Color(204, 255, 204));
        btn_shutdown.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_shutdown.setForeground(new java.awt.Color(0, 0, 0));
        btn_shutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shut Down.png"))); // NOI18N
        btn_shutdown.setText("Shut Down");
        btn_shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_shutdownActionPerformed(evt);
            }
        });
        getContentPane().add(btn_shutdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home background.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        btn_manageroom.setForeground(new JButton().getForeground());
        btn_manageroom.setBackground(new JButton().getBackground());
        
        btn_newstudent.setForeground(new JButton().getForeground());
        btn_newstudent.setBackground(new JButton().getBackground());
        
        btn_up_del_student.setForeground(new JButton().getForeground());
        btn_up_del_student.setBackground(new JButton().getBackground());
        
        btn_student_pay.setForeground(new JButton().getForeground());
        btn_student_pay.setBackground(new JButton().getBackground());
        
        btn_studentliving.setForeground(new JButton().getForeground());
        btn_studentliving.setBackground(new JButton().getBackground());
        
        btn_leveadstudent.setForeground(new JButton().getForeground());
        btn_leveadstudent.setBackground(new JButton().getBackground());
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You Want To LogOut","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You Want To Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_shutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_shutdownActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You Want To Shut Down","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            Runtime runtime=Runtime.getRuntime();
            try
            {
                Process proc=runtime.exec("shutdown -s -t 0");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_shutdownActionPerformed

    private void btn_manageroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageroomActionPerformed
        //TODO add your handling code here:
        btn_manageroom.setForeground(Color.RED);
        btn_manageroom.setBackground(new Color(255,255,255));
        
        new Manage_Room().setVisible(true);
    }//GEN-LAST:event_btn_manageroomActionPerformed

    private void btn_newstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newstudentActionPerformed
        // TODO add your handling code here:
        btn_newstudent.setForeground(Color.RED);
        btn_newstudent.setBackground(new Color(255,255,255));
        
        new Add_Student().setVisible(true);
        
    }//GEN-LAST:event_btn_newstudentActionPerformed

    private void btn_up_del_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_up_del_studentActionPerformed
        // TODO add your handling code here:
        btn_up_del_student.setForeground(Color.RED);
        btn_up_del_student.setBackground(new Color(255,255,255));
        
        new update_Delete().setVisible(true);
    }//GEN-LAST:event_btn_up_del_studentActionPerformed

    private void btn_student_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_student_payActionPerformed
        // TODO add your handling code here:
        btn_student_pay.setForeground(Color.RED);
        btn_student_pay.setBackground(new Color(255,255,255));
        
        new Student_Fees().setVisible(true);
    }//GEN-LAST:event_btn_student_payActionPerformed

    private void btn_studentlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentlivingActionPerformed
        // TODO add your handling code here:
        btn_studentliving.setForeground(Color.RED);
        btn_studentliving.setBackground(new Color(255,255,255));
        
        new All_Student_Living().setVisible(true);
    }//GEN-LAST:event_btn_studentlivingActionPerformed

    private void btn_leveadstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leveadstudentActionPerformed
        // TODO add your handling code here:
        btn_leveadstudent.setForeground(Color.RED);
        btn_leveadstudent.setBackground(new Color(255,255,255));
        
        new Leaved_Student().setVisible(true);
    }//GEN-LAST:event_btn_leveadstudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_leveadstudent;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manageroom;
    private javax.swing.JButton btn_newstudent;
    private javax.swing.JButton btn_shutdown;
    private javax.swing.JButton btn_student_pay;
    private javax.swing.JButton btn_studentliving;
    private javax.swing.JButton btn_up_del_student;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
